on: 
  push:
    branches:
    - main
    paths:
    - 'ae-02-bikeshare.qmd'  
name: Check Qmd
jobs:
  runs:
  using: 'composite'
  steps: 
    - name: 'Render'
      run: |
        if [ "${{ inputs.to }}" == "" ]; then
          quarto render ${{ inputs.path }}
        else
          quarto render ${{ inputs.path }} --to ${{ inputs.to }}
        fi
        if [ -f "_book" ]; then
          echo "QUARTO_OUTPUT=_book" >> $GITHUB_ENV
        elif [ -f "_site"]; then
          echo "QUARTO_OUTPUT=_site" >> $GITHUB_ENV
        fi
      shell: bash