on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

name: Render-qmd

jobs:
  render-qmd:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Quarto CLI
        uses: quarto-dev/quarto-actions/install-quarto@v1

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: "ae-02-bikeshare.qmd" # By default, the current working dir is used i.e `quarto render .`
        